version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Rome
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5432:5432"

  nextjs-app:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - logs-data:${LOGS_DIRECTORY} # logs volume
    ports:
      - "3000:3000" # next.js app
    depends_on:
      - db

volumes:
  postgres-data:
  logs-data:
